var worlds:[
    {
        id:1,
        name:"Marsh",
        zoom:1,
        background:"",
        waterColor:"red",
        color:"red",
        maxCity:2,
        waveTypes:[1,2,3]
    },
    {
        id:2,
        name:"River",
        zoom:2,
        background:"",
        waterColor:"blue",
        color:"blue",
        maxCity:3,
        waveTypes:[1,2,3,4,5,6]
    },
    {
        id:3,
        name:"Lake",
        zoom:3,
        background:"",
        waterColor:"yellow",
        color:"yellow",
        maxCity:4,
        waveTypes:[1,2,3,4,5,6,7,8,9]
    },
    {
        id:4,
        name:"Ocean",
        zoom:4,
        background:"",
        waterColor:"purple",
        color:"purple",
        maxCity:5,
        waveTypes:[1,2,3,4,5,6,7,8,9,10,11,12]
    },
];
