var Cities = [
    {
        id:1,
        name:"City 1",
        description:"City 1",
        image:"",
        cost:1000,
        damages:[
            {
                id:1,
                healthPercent:10,
                image:"",
            },
            {
                id:2,
                healthPercent:25,
                image:"",
            },
            {
                id:3,
                healthPercent:33,
                image:"",
            },
            {
                id:4,
                healthPercent:50,
                image:"",
            },
            {
                id:5,
                healthPercent:75,
                image:"",
            },
        ]
    },
    {
        id:2,
        name:"City 2",
        description:"City 2",
        image:"",
        cost:1000,
        damages:[
            {
                id:1,
                healthPercent:10,
                image:"",
            },
            {
                id:2,
                healthPercent:25,
                image:"",
            },
            {
                id:3,
                healthPercent:33,
                image:"",
            },
            {
                id:4,
                healthPercent:50,
                image:"",
            },
            {
                id:5,
                healthPercent:75,
                image:"",
            },
        ]
    },
    {
        id:3,
        name:"City 3",
        description:"City 3",
        image:"",
        cost:1000,
        damages:[
            {
                id:1,
                healthPercent:10,
                image:"",
            },
            {
                id:2,
                healthPercent:25,
                image:"",
            },
            {
                id:3,
                healthPercent:33,
                image:"",
            },
            {
                id:4,
                healthPercent:50,
                image:"",
            },
            {
                id:5,
                healthPercent:75,
                image:"",
            },
        ]
    },
    {
        id:4,
        name:"City 4",
        description:"City 4",
        image:"",
        cost:1000,
        damages:[
            {
                id:1,
                healthPercent:10,
                image:"",
            },
            {
                id:2,
                healthPercent:25,
                image:"",
            },
            {
                id:3,
                healthPercent:33,
                image:"",
            },
            {
                id:4,
                healthPercent:50,
                image:"",
            },
            {
                id:5,
                healthPercent:75,
                image:"",
            },
        ]
    },
    {
        id:5,
        name:"City 5",
        description:"City 5",
        image:"",
        cost:1000,
        damages:[
            {
                id:1,
                healthPercent:10,
                image:"",
            },
            {
                id:2,
                healthPercent:25,
                image:"",
            },
            {
                id:3,
                healthPercent:33,
                image:"",
            },
            {
                id:4,
                healthPercent:50,
                image:"",
            },
            {
                id:5,
                healthPercent:75,
                image:"",
            },
        ]
    },
];
